language: cpp
compiler:
- clang
- gcc
matrix:
  fast_finish: true
  allow_failures:
    - compiler: clang
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libboost-chrono1.48-dev libboost-date-time1.48-dev libboost-test1.48-dev libboost-system1.48-dev libboost-filesystem1.48-dev libboost-timer1.48-dev libboost-program-options1.48-dev libboost-thread1.48-dev python-yaml lcov
- gem install coveralls-lcov
script:
- mkdir -p build
- cd build
- cmake -DENABLE_ASAN:BOOL=ON -DENABLE_OPENCL=OFF ..
- make -j2
- ./examples/tutorial/viennacl-info
- ctest -j4 --output-on-failure

